DROP database if exists GRUPO4;
CREATE database GRUPO4;
USE GRUPO4;

CREATE TABLE CIUDAD (
ID_CIUDAD INT (100) auto_increment PRIMARY KEY,
NOMBRE VARCHAR(100),
PROVINCIA VARCHAR(100)
);
LOCK TABLES `CIUDAD` WRITE;

INSERT INTO CIUDAD VALUES (1,'Barcelona',''),(2,'Caceres',''),(3,'Teruel',''),(4,'Cuenca',''),(5,'Burgos',''),(6,'Ciudad Real',''),(7,'Cadiz',''),(8,'Castellon',''),(9,'Valencia',''),(10,'Zamora',''),(11,'Pontevedra',''),(12,'Tarragona',''),(13,'Madrid',''),(14,'Mallorca',''),(15,'Asturias',''),(16,'Tenerife',''),(17,'Gerona',''),(18,'Girona',''),(19,'Zaragoza',''),(20,'Granada','');
UNLOCK TABLES;

CREATE TABLE GENERO(
ID_GENERO INTEGER (100) auto_increment PRIMARY KEY,
NOMBRE varchar (100) NOT NULL
);

LOCK TABLES GENERO WRITE;
INSERT INTO GENERO VALUES (1,'Reggae'),(2,'Rock'),(3,'Jazz'),(4,'Pop'),(5,'Electro'),(6,'Post-Hardcore'),(7,'Dance'),(8,'Hip-Hop'),(9,'Flamenco'),(10,'Punk'),(11,'Salsa'),(12,'Rap');
UNLOCK TABLES;

CREATE TABLE USUARIOS(
ID_USUARIO integer(100) auto_increment primary KEY,
NOMBRE varchar(20),
APELLIDO  varchar(20),
TIPO INT (4),
USERNAME VARCHAR(20),
PASSWORD varchar(100),
EMAIL VARCHAR(320),
TELEFONO integer(20),
ID_CIUDAD integer (100),
FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE MUSICO(
ID_MUSICO INTEGER (100) auto_increment PRIMARY KEY,
NOMBRE_ARTISTICO  varchar(20),
ID_USUARIO integer(100),
ID_GENERO INTEGER (100), 
web VARCHAR (100),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO)
);

CREATE TABLE LOCALES(
ID_LOCAL INTEGER (100) auto_increment PRIMARY KEY, 
ID_USUARIO integer(100),
TIPO_LOCAL VARCHAR (100),
UBICACION VARCHAR (100),
AFORO integer(255),
IMAGEN VARCHAR(100),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE FAN(
ID_FAN INTEGER (100) auto_increment PRIMARY KEY, 
ID_USUARIO integer(100),
IMAGEN VARCHAR(100),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ENCUENTRO (
ID_MUSICO INTEGER (100),
ID_LOCAL INTEGER (100),
FECHA date,
HORA time,
COMENTARIO VARCHAR(100),
FOREIGN KEY (ID_MUSICO) REFERENCES MUSICO(ID_MUSICO),
FOREIGN KEY (ID_LOCAL) REFERENCES LOCALES(ID_LOCAL)
);

CREATE TABLE CONCIERTO (
ID_CONCIERTO INTEGER (100) auto_increment PRIMARY KEY,
FECHA date,
HORA time,
ID_LOCAL INTEGER (100),
PRECIO INTEGER(100),
ID_GENERO INTEGER (100),
ESTADO INTEGER (10),
FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO), 
FOREIGN KEY (ID_LOCAL) REFERENCES LOCALES(ID_LOCAL)
);

CREATE TABLE SOLICITUD_MUSICOS(
ID_MUSICO INTEGER (100),
ID_CONCIERTO INTEGER (100),
ESTADO INTEGER (10),
FOREIGN KEY (ID_MUSICO) REFERENCES MUSICO(ID_MUSICO),
FOREIGN KEY (ID_CONCIERTO) REFERENCES CONCIERTO(ID_CONCIERTO)
);

CREATE TABLE VOTOS(
ID_USUARIO INTEGER(100),
ID_FAN INTEGER (100),
VOTO BOOLEAN,
tipoVoto integer (2),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY (ID_FAN) REFERENCES FAN(ID_FAN)
);

